version: "3.9"
services:
  postgres_db:
    image: postgres
    container_name: cognixus_postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    volumes:
      - .:/app
    image: cognixus_django
    container_name: cognixus_todo_list
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_db 